name: 4. Robot Kompilasi Mingguan

on:
  workflow_dispatch:
  schedule:
    # Setiap Minggu Jam 03:00 WITA = Sabtu 19:00 UTC
    - cron: '0 19 * * 6'

jobs:
  compile_job:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install google-api-python-client google-auth-oauthlib google-auth-httplib2
      - name: Run Compile
        env:
          TOKEN_DATA: ${{ secrets.TOKEN_DATA }}
          input_video_id: ${{ secrets.input_video_id }}
          Gabungan_short_id: ${{ secrets.Gabungan_short_id }}
          Selesai_render_short_id: ${{ secrets.Selesai_render_short_id }}
          MUSIC_FOLDER_ID: ${{ secrets.MUSIC_FOLDER_ID }}
        run: python auto_compile_long.py
