name: Auto Rain Live Stream

on:
  schedule:
    - cron: '0 15 * * *' # Jam 22:00 WIB
  workflow_dispatch:      # Tombol manual

jobs:
  live_session:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Library
        run: pip install google-api-python-client google-auth-oauthlib google-auth-httplib2 google-generativeai

      - name: Jalankan Robot Live
        env:
          TOKEN_DATA: ${{ secrets.TOKEN_DATA }}
          SOURCE_LIVE_ID: ${{ secrets.SOURCE_LIVE_ID }}
          MUSIC_FOLDER_ID: ${{ secrets.MUSIC_FOLDER_ID }} # <--- BARIS INI WAJIB ADA
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_STREAM_KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
        run: python auto_live_rain.py

