name: Auto Rain Live Stream

on:
  schedule:
    # 15:00 UTC = 22:00 WIB
    - cron: '0 15 * * *'
  workflow_dispatch:      # Tombol manual di tab Actions

jobs:
  live_session:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v3

      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Library
        run: pip install google-api-python-client google-auth-oauthlib google-auth-httplib2 google-generativeai

      - name: Jalankan Robot Live Hujan
        env:
          # Mendukung TOKEN_DATA_LIVE (Akun berbeda) atau TOKEN_DATA (Akun sama)
          TOKEN_DATA_LIVE: ${{ secrets.TOKEN_DATA_LIVE }}
          TOKEN_DATA: ${{ secrets.TOKEN_DATA }}
          SOURCE_LIVE_ID: ${{ secrets.SOURCE_LIVE_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_STREAM_KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
        run: python auto_live_rain.py
