name: Auto Long Video Uploader

on:
  schedule:
    # Jam 02:30 UTC = Jam 09:30 WIB (Sekali sehari)
    - cron: '30 2 * * *'
  workflow_dispatch:      # Tombol untuk menjalankan manual

jobs:
  upload_long:
    runs-on: ubuntu-latest
    steps:
      - name: Ambil Kode
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Library
        run: pip install google-api-python-client google-auth-oauthlib google-auth-httplib2 google-generativeai

      - name: Jalankan Robot Video Panjang
        env:
          CLIENT_SECRETS_DATA: ${{ secrets.CLIENT_SECRETS_DATA }}
          TOKEN_DATA: ${{ secrets.TOKEN_DATA }}
          SOURCE_LONG_ID: ${{ secrets.SOURCE_LONG_ID }}
          PROCESSED_FOLDER_ID: ${{ secrets.PROCESSED_FOLDER_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          YOUTUBE_PRIVACY: ${{ secrets.YOUTUBE_PRIVACY }}
        run: python auto_long_uploader.py
