name: MICRO WILD - Live Stream System

on:
  workflow_dispatch: # Tombol jalankan manual
  schedule:
    - cron: '0 */4 * * *' # Otomatis jalan setiap 4 jam

jobs:
  streaming:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kode
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install google-api-python-client google-auth-oauthlib google-auth-httplib2
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Eksekusi Robot Live
        env:
          # Pastikan nama di bawah ini sama persis dengan yang ada di Settings > Secrets
          TOKEN_DATA: ${{ secrets.TOKEN_DATA }}
          CLIENT_SECRETS_DATA: ${{ secrets.CLIENT_SECRETS_DATA }}
          SOURCE_LIVE_ID: ${{ secrets.SOURCE_LIVE_ID }}
          MUSIC_FOLDER_ID: ${{ secrets.MUSIC_FOLDER_ID }}
          YOUTUBE_STREAM_KEY: ${{ secrets.YOUTUBE_STREAM_KEY }}
        run: python auto_live_rain.py